# Generated by Django 4.2.1 on 2023-06-30 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_courier_job_courier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courier',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='courier',
            name='lng',
        ),
    ]
